# Site settings
title: LeftDevel
email: oscar@leftdevel.com
description: > # this means to ignore newlines until "baseurl:"
  Oscar's blog about web technologies and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leftdevel.com" # the base hostname & protocol for your site
twitter_username: leftdevel
github_username:  leftdevel

# Build settings
markdown: kramdown
permalink: /blog/:title